// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */

  mySidebar: [
    'intro',
    {
      type: 'category',
      label: 'Animations',
      link: {
        type: 'doc',
        id: 'animations/introduction',
      },
      items: [
        {
          type: 'category',
          label: 'Functions',
          items: [
            {
              type: 'category',
              label: 'Client',
              link: {
                type: 'doc',
                id: 'animations/functions/client/client',
              },
              items: [
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Anti Bump',
      link: {
        type: 'doc',
        id: 'antibump/introduction',
      },
      items: [
        {
          type: 'category',
          label: 'Functions',
          items: [
            {
              type: 'category',
              label: 'Client',
              link: {
                type: 'doc',
                id: 'antibump/functions/client/client',
              },
              items: [
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Guides',
          link: {
            type: 'doc',
            id: 'antibump/guides/introduction',
          },
          items: [
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Prime Control',
      link: {
        type: 'doc',
        id: 'primecontrol/introduction',
      },
      items: [
        {
          type: 'category',
          label: 'Functions',
          items: [
            {
              type: 'category',
              label: 'Client',
              link: {
                type: 'doc',
                id: 'primecontrol/functions/client/client',
              },
              items: [
              ],
            },
            {
              type: 'category',
              label: 'Server',
              link: {
                type: 'doc',
                id: 'primecontrol/functions/server/server',
              },
              items: [
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Guides',
          link: {
            type: 'doc',
            id: 'primecontrol/guides/introduction',
          },
          items: [
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Remapping',
      link: {
        type: 'doc',
        id: 'remapping/introduction',
      },
      items: [
        {
          type: 'category',
          label: 'Functions',
          items: [
            {
              type: 'category',
              label: 'Client',
              link: {
                type: 'doc',
                id: 'remapping/functions/client/client',
              },
              items: [
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Skin Weapon',
      link: {
        type: 'doc',
        id: 'skinweapon/introduction',
      },
      items: [
        {
          type: 'category',
          label: 'Functions',
          items: [
            {
              type: 'category',
              label: 'Server',
              link: {
                type: 'doc',
                id: 'skinweapon/functions/server/server',
              },
              items: [
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Stance Tuning',
      link: {
        type: 'doc',
        id: 'stancetuning/introduction',
      },
      items: [
        {
          type: 'category',
          label: 'Functions',
          items: [
            {
              type: 'category',
              label: 'Client',
              link: {
                type: 'doc',
                id: 'stancetuning/functions/client/client',
              },
              items: [
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Guides',
          link: {
            type: 'doc',
            id: 'stancetuning/guides/introduction',
          },
          items: [
          ],
        },
      ],
    },
  ],
};

export default sidebars;
